"""Reviewed agent operations. Effects are explicit, never inferred at runtime."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict


class ToolDefinition(BaseModel):
    model_config = ConfigDict(frozen=True)
    name: str
    method: str
    path: str
    path_params: tuple[str, ...]
    effect: Literal["read", "write", "delete", "external", "execute", "interact"]
    admin_only: bool = False

    @property
    def parallel_safe(self) -> bool:
        return self.effect == "read"


# Explicit migration of the reviewed gateway catalog; new operations require review.
_OPERATIONS = {
    "computer_use.browser_fetch": ("POST", "/api/computer-use/execute", [], "read", False),
    "computer_use.web_discover": ("POST", "/api/computer-use/web-discover", [], "read", False),
    "computer_use.desktop_snapshot": ("POST", "/api/computer-use/execute", [], "read", False),
    "computer_use.desktop_start": ("POST", "/api/computer-use/execute", [], "interact", False),
    "computer_use.desktop_click": ("POST", "/api/computer-use/execute", [], "interact", False),
    "computer_use.desktop_type": ("POST", "/api/computer-use/execute", [], "interact", False),
    "computer_use.desktop_read": ("POST", "/api/computer-use/execute", [], "read", False),
    "computer_use.desktop_close": ("POST", "/api/computer-use/execute", [], "interact", False),
    "computer_use.file_read": ("POST", "/api/computer-use/execute", [], "read", False),
    "computer_use.file_write": ("POST", "/api/computer-use/execute", [], "write", False),
    "computer_use.shell": ("POST", "/api/computer-use/execute", [], "execute", False),
    "tool_catalog.create_supplier": ("POST", "/api/tool-catalog/suppliers", [], "write", False),
    "tool_catalog.resolve_supplier": (
        "POST",
        "/api/tool-catalog/resolve-supplier",
        [],
        "write",
        False,
    ),
    "tool_catalog.discover_catalogs": (
        "POST",
        "/api/tool-catalog/discover-catalogs",
        [],
        "write",
        False,
    ),
    "tool_catalog.attach_web_catalog": (
        "POST",
        "/api/tool-catalog/attach-web-catalog",
        [],
        "write",
        False,
    ),
    "tool_catalog.ingest_status": ("POST", "/api/tool-catalog/ingest-status", [], "read", False),
    "tool_catalog.ingest_web_source": (
        "POST",
        "/api/tool-catalog/suppliers/{supplier_id}/ingest-web-source",
        ["supplier_id"],
        "write",
        False,
    ),
    "tool_catalog.list_entries": (
        "GET",
        "/api/tool-catalog/by-supplier/{party_id}/entries",
        ["party_id"],
        "read",
        False,
    ),
    "tool_catalog.approve": (
        "POST",
        "/api/tool-catalog/entries/{entry_id}/approve",
        ["entry_id"],
        "write",
        False,
    ),
    "tool_catalog.crawl_site": ("POST", "/api/tool-catalog/crawl-site", [], "write", False),
    "tool_catalog.list_catalogs": ("GET", "/api/catalogs", [], "read", False),
    "tool_catalog.catalog_pages": (
        "GET",
        "/api/catalogs/{document_id}/pages",
        ["document_id"],
        "read",
        False,
    ),
    "tool_catalog.search_positions": ("POST", "/api/catalogs/search", [], "read", False),
    "tool_catalog.pause_parsing": (
        "POST",
        "/api/catalogs/{document_id}/pause",
        ["document_id"],
        "write",
        False,
    ),
    "tool_catalog.similar_positions": ("POST", "/api/catalogs/similar", [], "read", False),
    "tool_catalog.search_visual": ("POST", "/api/catalogs/search-visual", [], "read", False),
    "tool_catalog.list_uploads": (
        "GET",
        "/api/tool-catalog/by-supplier/{party_id}/uploads",
        ["party_id"],
        "read",
        False,
    ),
    "tool_catalog.reingest_upload": (
        "POST",
        "/api/tool-catalog/uploads/{document_id}/reingest",
        ["document_id"],
        "write",
        False,
    ),
    "tool_catalog.refresh": (
        "POST",
        "/api/tool-catalog/suppliers/{supplier_id}/refresh",
        ["supplier_id"],
        "write",
        False,
    ),
    "documents.list": ("GET", "/api/documents", [], "read", False),
    "documents.get": ("GET", "/api/documents/{document_id}", ["document_id"], "read", False),
    "documents.search": ("POST", "/api/search/documents", [], "read", False),
    "documents.ingest": ("POST", "/api/documents/ingest", [], "write", False),
    "documents.classify": (
        "POST",
        "/api/documents/{document_id}/classify",
        ["document_id"],
        "write",
        False,
    ),
    "documents.extract": (
        "POST",
        "/api/documents/{document_id}/extract",
        ["document_id"],
        "write",
        False,
    ),
    "documents.summarize": (
        "POST",
        "/api/documents/{document_id}/summarize",
        ["document_id"],
        "write",
        False,
    ),
    "documents.update": ("PATCH", "/api/documents/{document_id}", ["document_id"], "write", False),
    "documents.delete": (
        "DELETE",
        "/api/documents/{document_id}",
        ["document_id"],
        "delete",
        False,
    ),
    "documents.bulk_delete": ("DELETE", "/api/documents/bulk-delete", [], "delete", False),
    "documents.link": (
        "POST",
        "/api/documents/{document_id}/links",
        ["document_id"],
        "write",
        False,
    ),
    "documents.dependencies": (
        "GET",
        "/api/documents/{document_id}/dependencies",
        ["document_id"],
        "read",
        False,
    ),
    "documents.queue": ("GET", "/api/documents/workspace", [], "read", False),
    "documents.processing_status": (
        "GET",
        "/api/documents/{document_id}/management",
        ["document_id"],
        "read",
        False,
    ),
    "documents.reprocess": (
        "POST",
        "/api/documents/{document_id}/classify",
        ["document_id"],
        "write",
        False,
    ),
    "invoices.list": ("GET", "/api/invoices", [], "read", False),
    "invoices.get": ("GET", "/api/invoices/{invoice_id}", ["invoice_id"], "read", False),
    "invoices.validate": (
        "POST",
        "/api/invoices/{invoice_id}/validate",
        ["invoice_id"],
        "write",
        False,
    ),
    "invoices.approve": (
        "POST",
        "/api/invoices/{invoice_id}/approve",
        ["invoice_id"],
        "write",
        False,
    ),
    "invoices.reject": (
        "POST",
        "/api/invoices/{invoice_id}/reject",
        ["invoice_id"],
        "write",
        False,
    ),
    "invoices.compare_prices": (
        "GET",
        "/api/invoices/{invoice_id}/price-check",
        ["invoice_id"],
        "read",
        False,
    ),
    "invoices.catalog_price_check": (
        "GET",
        "/api/invoices/{invoice_id}/catalog-price-check",
        ["invoice_id"],
        "read",
        False,
    ),
    "invoices.export_excel": (
        "POST",
        "/api/invoices/{invoice_id}/export",
        ["invoice_id"],
        "write",
        False,
    ),
    "invoices.export_1c": (
        "POST",
        "/api/invoices/{invoice_id}/export-1c",
        ["invoice_id"],
        "write",
        False,
    ),
    "invoices.update": ("PATCH", "/api/invoices/{invoice_id}", ["invoice_id"], "write", False),
    "invoices.delete": ("DELETE", "/api/invoices/{invoice_id}", ["invoice_id"], "delete", False),
    "invoices.bulk_delete": ("DELETE", "/api/invoices", [], "delete", False),
    "invoices.bulk_approve": ("POST", "/api/invoices/bulk-approve", [], "write", False),
    "invoices.bulk_reject": ("POST", "/api/invoices/bulk-reject", [], "write", False),
    "invoices.receive": (
        "POST",
        "/api/invoices/{invoice_id}/receive",
        ["invoice_id"],
        "write",
        False,
    ),
    "suppliers.list": ("GET", "/api/suppliers", [], "read", False),
    "suppliers.get": ("GET", "/api/suppliers/{supplier_id}", ["supplier_id"], "read", False),
    "suppliers.search": ("POST", "/api/suppliers/search", [], "read", False),
    "suppliers.price_history": (
        "GET",
        "/api/suppliers/{supplier_id}/price-history",
        ["supplier_id"],
        "read",
        False,
    ),
    "suppliers.trust_score": (
        "GET",
        "/api/suppliers/{supplier_id}/trust-score",
        ["supplier_id"],
        "read",
        False,
    ),
    "suppliers.alerts": (
        "GET",
        "/api/suppliers/{supplier_id}/alerts",
        ["supplier_id"],
        "read",
        False,
    ),
    "suppliers.update": ("PATCH", "/api/suppliers/{supplier_id}", ["supplier_id"], "write", False),
    "suppliers.check_requisites": (
        "POST",
        "/api/suppliers/{supplier_id}/check-requisites",
        ["supplier_id"],
        "write",
        False,
    ),
    "warehouse.list_inventory": ("GET", "/api/warehouse/inventory", [], "read", False),
    "warehouse.get_item": ("GET", "/api/warehouse/inventory/{item_id}", ["item_id"], "read", False),
    "warehouse.low_stock": ("GET", "/api/warehouse/inventory/low-stock", [], "read", False),
    "warehouse.create_receipt": ("POST", "/api/warehouse/receipts", [], "write", False),
    "warehouse.confirm_receipt": (
        "POST",
        "/api/warehouse/receipts/{receipt_id}/confirm",
        ["receipt_id"],
        "write",
        False,
    ),
    "warehouse.issue_stock": (
        "POST",
        "/api/warehouse/inventory/{item_id}/issue",
        ["item_id"],
        "write",
        False,
    ),
    "warehouse.adjust_stock": (
        "POST",
        "/api/warehouse/inventory/{item_id}/adjust",
        ["item_id"],
        "write",
        False,
    ),
    "warehouse.list_receipts": ("GET", "/api/warehouse/receipts", [], "read", False),
    "warehouse.get_receipt": (
        "GET",
        "/api/warehouse/receipts/{receipt_id}",
        ["receipt_id"],
        "read",
        False,
    ),
    "warehouse.list_movements": ("GET", "/api/warehouse/movements", [], "read", False),
    "warehouse.create_item": ("POST", "/api/warehouse/inventory", [], "write", False),
    "warehouse.update_item": (
        "PATCH",
        "/api/warehouse/inventory/{item_id}",
        ["item_id"],
        "write",
        False,
    ),
    "warehouse.delete_item": (
        "DELETE",
        "/api/warehouse/inventory/{item_id}",
        ["item_id"],
        "delete",
        False,
    ),
    "warehouse.bulk_confirm": ("POST", "/api/warehouse/receipts/bulk-confirm", [], "write", False),
    "warehouse.update_status": (
        "PATCH",
        "/api/warehouse/receipts/{receipt_id}/status",
        ["receipt_id"],
        "write",
        False,
    ),
    "email.list": ("GET", "/api/email/threads", [], "read", False),
    "email.search": ("POST", "/api/email/search", [], "read", False),
    "email.get": ("GET", "/api/email/threads/{thread_id}", ["thread_id"], "read", False),
    "email.draft": ("POST", "/api/email/drafts", [], "write", False),
    "email.send": ("POST", "/api/email/drafts/{draft_id}/send", ["draft_id"], "external", False),
    "email.fetch_new": ("POST", "/api/email/fetch", [], "write", False),
    "email.risk_check": (
        "POST",
        "/api/email/drafts/{draft_id}/risk-check",
        ["draft_id"],
        "write",
        False,
    ),
    "email.list_templates": ("GET", "/api/email-templates/", [], "read", False),
    "email.get_template": (
        "GET",
        "/api/email-templates/{template_id}",
        ["template_id"],
        "read",
        False,
    ),
    "email.render_template": (
        "POST",
        "/api/email-templates/{template_id}/render",
        ["template_id"],
        "read",
        False,
    ),
    "email.delete_template": (
        "DELETE",
        "/api/email-templates/{template_id}",
        ["template_id"],
        "delete",
        False,
    ),
    "email.suggest_template": ("POST", "/api/email/suggest-template", [], "write", False),
    "email.style_match": ("POST", "/api/email/style-analyze", [], "write", False),
    "email.my_mailbox": ("GET", "/api/mailbox/me", [], "read", False),
    "email.process_attachment": (
        "POST",
        "/api/email/messages/{message_id}/attachments/process",
        ["message_id"],
        "write",
        False,
    ),
    "email.list_threads": ("GET", "/api/email/threads", [], "read", False),
    "email.get_thread": ("GET", "/api/email/threads/{thread_id}", ["thread_id"], "read", False),
    "email.read": ("GET", "/api/email/{email_id}", ["email_id"], "read", False),
    "email.list_drafts": ("GET", "/api/email/drafts", [], "read", False),
    "email.get_draft": ("GET", "/api/email/drafts/{draft_id}", ["draft_id"], "read", False),
    "email.mailboxes": ("GET", "/api/email/mailboxes", [], "read", False),
    "email.labels": ("GET", "/api/email/labels", [], "read", False),
    "email.label": ("POST", "/api/email/threads/actions", [], "write", False),
    "email.compose": ("POST", "/api/email/compose/generate", [], "write", False),
    "email.compose_assist": ("POST", "/api/email/compose/assist", [], "read", False),
    "email.reply": (
        "POST",
        "/api/email/threads/{thread_id}/reply-draft",
        ["thread_id"],
        "write",
        False,
    ),
    "email.get_attachment": (
        "GET",
        "/api/email/messages/{message_id}/attachments/{filename}/content",
        ["message_id", "filename"],
        "read",
        False,
    ),
    "email.recognize_attachment": (
        "POST",
        "/api/email/messages/{message_id}/attachments/recognize",
        ["message_id"],
        "write",
        False,
    ),
    "email.templates.list": ("GET", "/api/email-templates/", [], "read", False),
    "email.templates.get": (
        "GET",
        "/api/email-templates/{template_id}",
        ["template_id"],
        "read",
        False,
    ),
    "email.templates.render": (
        "POST",
        "/api/email-templates/{template_id}/render",
        ["template_id"],
        "read",
        False,
    ),
    "email.templates.delete": (
        "DELETE",
        "/api/email-templates/{template_id}",
        ["template_id"],
        "delete",
        False,
    ),
    "email.templates.create": ("POST", "/api/email-templates/", [], "write", False),
    "email.templates.update": (
        "PATCH",
        "/api/email-templates/{template_id}",
        ["template_id"],
        "write",
        False,
    ),
    "email.templates.from_message": (
        "POST",
        "/api/email-templates/from-message",
        [],
        "write",
        False,
    ),
    "procurement.list_requests": ("GET", "/api/purchase-requests", [], "read", False),
    "procurement.create_request": ("POST", "/api/purchase-requests", [], "write", False),
    "procurement.get_request": (
        "GET",
        "/api/purchase-requests/{request_id}",
        ["request_id"],
        "read",
        False,
    ),
    "procurement.update_request": (
        "PATCH",
        "/api/purchase-requests/{request_id}",
        ["request_id"],
        "write",
        False,
    ),
    "procurement.send_rfq": (
        "POST",
        "/api/purchase-requests/{request_id}/send-rfq",
        ["request_id"],
        "external",
        False,
    ),
    "procurement.list_contracts": ("GET", "/api/compare", [], "read", False),
    "procurement.create_contract": ("POST", "/api/compare", [], "write", False),
    "procurement.get_contract": (
        "GET",
        "/api/compare/{contract_id}",
        ["contract_id"],
        "read",
        False,
    ),
    "procurement.update_contract": (
        "PATCH",
        "/api/supplier-contracts/{contract_id}",
        ["contract_id"],
        "write",
        False,
    ),
    "payments.list_schedule": ("GET", "/api/payment-schedules", [], "read", False),
    "payments.overdue": ("GET", "/api/payment-schedules/overdue", [], "read", False),
    "payments.upcoming": ("GET", "/api/payment-schedules/upcoming", [], "read", False),
    "payments.mark_paid": (
        "POST",
        "/api/payment-schedules/{schedule_id}/mark-paid",
        ["schedule_id"],
        "write",
        False,
    ),
    "payments.create_schedule": ("POST", "/api/payment-schedules", [], "write", False),
    "payments.calendar": ("GET", "/api/calendar/upcoming", [], "read", False),
    "anomalies.list": ("GET", "/api/anomalies", [], "read", False),
    "anomalies.check_all": ("POST", "/api/anomalies/check", [], "write", False),
    "anomalies.explain": (
        "GET",
        "/api/anomalies/{anomaly_id}/explain",
        ["anomaly_id"],
        "read",
        False,
    ),
    "anomalies.resolve": (
        "POST",
        "/api/anomalies/{anomaly_id}/resolve",
        ["anomaly_id"],
        "write",
        False,
    ),
    "anomalies.create_card": ("POST", "/api/anomalies", [], "write", False),
    "normalization.list_rules": ("GET", "/api/normalization/rules", [], "read", False),
    "normalization.suggest_rule": ("POST", "/api/normalization/suggest", [], "write", False),
    "normalization.activate_rule": (
        "POST",
        "/api/normalization/rules/{rule_id}/activate",
        ["rule_id"],
        "write",
        False,
    ),
    "normalization.apply_rules": ("POST", "/api/normalization/apply", [], "write", False),
    "normalization.list_norm_cards": ("GET", "/api/normalization/norm-cards", [], "read", False),
    "normalization.create_norm_card": ("POST", "/api/normalization/norm-cards", [], "write", False),
    "normalization.update_norm_card": (
        "PATCH",
        "/api/normalization/norm-cards/{card_id}",
        ["card_id"],
        "write",
        False,
    ),
    "normalization.list_canonical_items": (
        "GET",
        "/api/normalization/canonical-items",
        [],
        "read",
        False,
    ),
    "normalization.get_canonical_item": (
        "GET",
        "/api/normalization/canonical-items/{item_id}",
        ["item_id"],
        "read",
        False,
    ),
    "normalization.update_canonical_item": (
        "PATCH",
        "/api/normalization/canonical-items/{item_id}",
        ["item_id"],
        "write",
        False,
    ),
    "workspace.spec_table": ("POST", "/api/workspace/agent/spec-table", [], "write", False),
    "workspace.spec_table_patch": (
        "POST",
        "/api/workspace/agent/spec-table/patch",
        [],
        "write",
        False,
    ),
    "workspace.spec_table_catalog": (
        "GET",
        "/api/workspace/agent/spec-table/catalog",
        [],
        "read",
        False,
    ),
    "workspace.spec_table_cell_edit": (
        "POST",
        "/api/workspace/agent/spec-table/cell-edit",
        [],
        "write",
        False,
    ),
    "workspace.invoice_table": ("POST", "/api/workspace/agent/invoices/table", [], "write", False),
    "workspace.invoice_items_table": (
        "POST",
        "/api/workspace/agent/invoices/items-table",
        [],
        "write",
        False,
    ),
    "workspace.invoice_items_grouped": (
        "POST",
        "/api/workspace/agent/invoices/items-grouped-table",
        [],
        "write",
        False,
    ),
    "workspace.invoice_items_by_supplier": (
        "POST",
        "/api/workspace/agent/invoices/items-by-supplier-table",
        [],
        "write",
        False,
    ),
    "workspace.invoice_pivot": (
        "POST",
        "/api/workspace/agent/invoices/pivot-table",
        [],
        "write",
        False,
    ),
    "workspace.general": ("POST", "/api/workspace/agent/generated/general", [], "write", False),
    "workspace.sql_table": ("POST", "/api/workspace/agent/generated/sql-table", [], "write", False),
    "workspace.compare_table_data": (
        "POST",
        "/api/workspace/agent/compare-table-data",
        [],
        "write",
        False,
    ),
    "workspace.supplier_lookup": ("POST", "/api/suppliers/search", [], "read", False),
    "workspace.verify": ("POST", "/api/workspace/agent/verify-block", [], "read", False),
    "workspace.get_block": (
        "GET",
        "/api/workspace/blocks/{canvas_id}",
        ["canvas_id"],
        "read",
        False,
    ),
    "sheets.create": ("POST", "/api/workspace/sheets/create", [], "write", False),
    "sheets.list": ("GET", "/api/workspace/sheets", [], "read", False),
    "sheets.get": ("GET", "/api/workspace/sheets/{sheet_id}", ["sheet_id"], "read", False),
    "sheets.patch_cells": (
        "POST",
        "/api/workspace/sheets/{sheet_id}/patch-cells",
        ["sheet_id"],
        "write",
        False,
    ),
    "sheets.add_row": (
        "POST",
        "/api/workspace/sheets/{sheet_id}/add-row",
        ["sheet_id"],
        "write",
        False,
    ),
    "sheets.add_column": (
        "POST",
        "/api/workspace/sheets/{sheet_id}/add-column",
        ["sheet_id"],
        "write",
        False,
    ),
    "sheets.set_formula": (
        "POST",
        "/api/workspace/sheets/{sheet_id}/set-formula",
        ["sheet_id"],
        "write",
        False,
    ),
    "sheets.rename_column": (
        "POST",
        "/api/workspace/sheets/{sheet_id}/rename-column",
        ["sheet_id"],
        "write",
        False,
    ),
    "sheets.merge_cells": (
        "POST",
        "/api/workspace/sheets/{sheet_id}/merge-cells",
        ["sheet_id"],
        "write",
        False,
    ),
    "sheets.unmerge_cells": (
        "POST",
        "/api/workspace/sheets/{sheet_id}/unmerge-cells",
        ["sheet_id"],
        "write",
        False,
    ),
    "sheets.delete": ("DELETE", "/api/workspace/sheets/{sheet_id}", ["sheet_id"], "delete", False),
    "sheets.from_spec": ("POST", "/api/workspace/sheets/from-spec", [], "write", False),
    "sheets.from_template": ("POST", "/api/workspace/sheets/from-template", [], "write", False),
    "sheets.templates": ("GET", "/api/workspace/sheets/templates/list", [], "read", False),
    "search.hybrid": ("POST", "/api/search/hybrid", [], "read", False),
    "search.nl": ("POST", "/api/search/nl", [], "read", False),
    "search.nl_to_query": ("POST", "/api/search/nl", [], "read", False),
    "search.web": ("POST", "/api/web-search/query", [], "read", False),
    "search.browse": ("POST", "/api/web-search/fetch", [], "read", False),
    "search.research": ("POST", "/api/web-search/research", [], "read", False),
    "search.explain": ("POST", "/api/memory/explain", [], "read", False),
    "search.similar": (
        "GET",
        "/api/search/similar/{entity_type}/{entity_id}",
        ["entity_type", "entity_id"],
        "read",
        False,
    ),
    "search.saved_queries": ("GET", "/api/search/saved-queries", [], "read", False),
    "memory.query": ("POST", "/api/memory/query", [], "read", False),
    "memory.search": ("POST", "/api/memory/search", [], "read", False),
    "memory.explain": ("POST", "/api/memory/explain", [], "read", False),
    "memory.promote": ("POST", "/api/memory/promotions", [], "write", False),
    "memory.promotion_list": ("GET", "/api/memory/promotions", [], "read", False),
    "memory.promotion_evaluate": (
        "POST",
        "/api/memory/promotions/{entity_id}/evaluate",
        ["entity_id"],
        "write",
        False,
    ),
    "memory.promotion_decide": (
        "POST",
        "/api/memory/promotions/{entity_id}/decide",
        ["entity_id"],
        "write",
        True,
    ),
    "memory.source_propose": ("POST", "/api/memory/sources/propose", [], "write", False),
    "memory.source_list": ("GET", "/api/memory/sources", [], "read", False),
    "memory.source_discover": ("POST", "/api/memory/sources/discover", [], "write", False),
    "memory.source_decide": (
        "POST",
        "/api/memory/sources/{entity_id}/decide",
        ["entity_id"],
        "write",
        True,
    ),
    "memory.reindex": ("POST", "/api/memory/reindex", [], "write", False),
    "memory.embeddings_stats": ("GET", "/api/memory/embeddings/stats", [], "read", False),
    "memory.embeddings_rebuild": ("POST", "/api/memory/embeddings/rebuild", [], "write", False),
    "memory.embeddings_rebuild_active": (
        "POST",
        "/api/memory/embeddings/rebuild-active",
        [],
        "write",
        False,
    ),
    "memory.embeddings_index_active": (
        "POST",
        "/api/memory/embeddings/index-active",
        [],
        "write",
        False,
    ),
    "memory.prune": ("POST", "/api/memory/prune", [], "delete", False),
    "memory.neighborhood": (
        "GET",
        "/api/graph/nodes/{node_id}/neighborhood",
        ["node_id"],
        "read",
        False,
    ),
    "memory.path": ("GET", "/api/graph/path", [], "read", False),
    "tech.process_plan_list": ("GET", "/api/technology/process-plans", [], "read", False),
    "tech.process_plan_get": (
        "GET",
        "/api/technology/process-plans/{entity_id}",
        ["entity_id"],
        "read",
        False,
    ),
    "tech.process_plan_create": ("POST", "/api/technology/process-plans", [], "write", False),
    "tech.process_plan_validate": (
        "POST",
        "/api/technology/process-plans/{entity_id}/validate",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.process_plan_approve": (
        "POST",
        "/api/technology/process-plans/{entity_id}/approve",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.operation_add": (
        "POST",
        "/api/technology/process-plans/{entity_id}/operations",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.operation_template_list": (
        "GET",
        "/api/technology/operation-templates",
        [],
        "read",
        False,
    ),
    "tech.norm_estimate_create": (
        "POST",
        "/api/technology/process-plans/{entity_id}/norm-estimates",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.norm_estimate_suggest": (
        "POST",
        "/api/technology/process-plans/{entity_id}/estimate-norms",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.norm_estimate_approve": (
        "POST",
        "/api/technology/norm-estimates/{entity_id}/approve",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.resource_list": ("GET", "/api/technology/resources", [], "read", False),
    "tech.resource_create": ("POST", "/api/technology/resources", [], "write", False),
    "tech.bom_list": ("GET", "/api/boms", [], "read", False),
    "tech.bom_get": ("GET", "/api/boms/{entity_id}", ["entity_id"], "read", False),
    "tech.bom_create": ("POST", "/api/boms", [], "write", False),
    "tech.bom_update": ("PATCH", "/api/boms/{entity_id}", ["entity_id"], "write", False),
    "tech.bom_approve": ("POST", "/api/boms/{entity_id}/approve", ["entity_id"], "write", False),
    "tech.bom_stock_check": (
        "GET",
        "/api/boms/{entity_id}/stock-check",
        ["entity_id"],
        "read",
        False,
    ),
    "tech.bom_purchase_request": (
        "POST",
        "/api/boms/{entity_id}/create-purchase-request",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.ntd_list": ("GET", "/api/ntd/documents", [], "read", False),
    "tech.ntd_get": ("GET", "/api/ntd/checks/{entity_id}", ["entity_id"], "read", False),
    "tech.ntd_run_check": ("POST", "/api/ntd/checks/run", [], "write", False),
    "tech.ntd_findings": ("GET", "/api/ntd/requirements/search", [], "read", False),
    "tech.learning_suggest": ("GET", "/api/technology/learning-suggestions", [], "read", False),
    "tech.learning_rule_list": ("GET", "/api/technology/learning-rules", [], "read", False),
    "tech.learning_rule_create": ("POST", "/api/technology/learning-rules", [], "write", False),
    "tech.learning_rule_activate": (
        "POST",
        "/api/technology/learning-rules/{entity_id}/activate",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.learning_rule_reject": (
        "POST",
        "/api/technology/learning-rules/{entity_id}/reject",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.correction_record": ("POST", "/api/technology/corrections", [], "write", False),
    "tech.process_plan_draft_from_document": (
        "POST",
        "/api/technology/process-plans/draft-from-document",
        [],
        "write",
        False,
    ),
    "tech.generate_tp_from_drawing": (
        "POST",
        "/api/technology/process-plans/generate-from-drawing",
        [],
        "write",
        False,
    ),
    "tech.analyze_surfaces": (
        "POST",
        "/api/technology/process-plans/{entity_id}/analyze-surfaces",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.select_equipment_for_op": (
        "POST",
        "/api/technology/process-plans/{entity_id}/select-equipment",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.calculate_cutting_params": (
        "POST",
        "/api/technology/process-plans/{entity_id}/calculate-cutting-params",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.normcontrol_check": (
        "POST",
        "/api/technology/process-plans/{entity_id}/normcontrol",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.normcontrol_resolve": (
        "POST",
        "/api/technology/process-plans/{entity_id}/normcontrol/{check_id}/resolve",
        ["entity_id", "check_id"],
        "write",
        False,
    ),
    "tech.blank_spec_set": (
        "POST",
        "/api/technology/process-plans/{entity_id}/blank-spec",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.surface_specs_list": (
        "GET",
        "/api/technology/process-plans/{entity_id}/surface-specs",
        ["entity_id"],
        "read",
        False,
    ),
    "tech.export_gost_forms": (
        "POST",
        "/api/technology/process-plans/{entity_id}/export-gost",
        ["entity_id"],
        "write",
        False,
    ),
    "tech.operation_template_create": (
        "POST",
        "/api/technology/operation-templates",
        [],
        "write",
        False,
    ),
    "engineering.material_list": ("GET", "/api/engineering/materials", [], "read", False),
    "engineering.material_create": ("POST", "/api/engineering/materials", [], "write", False),
    "engineering.project_list": ("GET", "/api/engineering/projects", [], "read", False),
    "engineering.project_get": (
        "GET",
        "/api/engineering/projects/{entity_id}",
        ["entity_id"],
        "read",
        False,
    ),
    "engineering.project_create": ("POST", "/api/engineering/projects", [], "write", False),
    "engineering.revision_create": (
        "POST",
        "/api/engineering/projects/{entity_id}/revisions",
        ["entity_id"],
        "write",
        False,
    ),
    "engineering.projection_list": (
        "GET",
        "/api/engineering/revisions/{entity_id}/projections",
        ["entity_id"],
        "read",
        False,
    ),
    "engineering.projection_create": (
        "POST",
        "/api/engineering/revisions/{entity_id}/projections",
        ["entity_id"],
        "write",
        False,
    ),
    "engineering.material_assignment_list": (
        "GET",
        "/api/engineering/revisions/{entity_id}/materials",
        ["entity_id"],
        "read",
        False,
    ),
    "engineering.material_assign": (
        "POST",
        "/api/engineering/revisions/{entity_id}/materials",
        ["entity_id"],
        "write",
        False,
    ),
    "engineering.assembly_list": (
        "GET",
        "/api/engineering/revisions/{entity_id}/assemblies",
        ["entity_id"],
        "read",
        False,
    ),
    "engineering.assembly_create": (
        "POST",
        "/api/engineering/revisions/{entity_id}/assemblies",
        ["entity_id"],
        "write",
        False,
    ),
    "engineering.assembly_component_add": (
        "POST",
        "/api/engineering/assemblies/{entity_id}/components",
        ["entity_id"],
        "write",
        False,
    ),
    "engineering.assembly_mate_add": (
        "POST",
        "/api/engineering/assemblies/{entity_id}/mates",
        ["entity_id"],
        "write",
        False,
    ),
    "engineering.assembly_validate": (
        "POST",
        "/api/engineering/assemblies/{entity_id}/validate",
        ["entity_id"],
        "write",
        False,
    ),
    "engineering.revision_validate": (
        "POST",
        "/api/engineering/revisions/{entity_id}/validate",
        ["entity_id"],
        "write",
        False,
    ),
    "engineering.validation_run_list": (
        "GET",
        "/api/engineering/revisions/{entity_id}/validation-runs",
        ["entity_id"],
        "read",
        False,
    ),
    "engineering.analysis_case_list": (
        "GET",
        "/api/engineering/revisions/{entity_id}/analysis-cases",
        ["entity_id"],
        "read",
        False,
    ),
    "engineering.analysis_case_create": (
        "POST",
        "/api/engineering/revisions/{entity_id}/analysis-cases",
        ["entity_id"],
        "write",
        False,
    ),
    "engineering.analysis_case_run": (
        "POST",
        "/api/engineering/analysis-cases/{entity_id}/run",
        ["entity_id"],
        "write",
        False,
    ),
    "engineering.revision_approve": (
        "POST",
        "/api/engineering/revisions/{entity_id}/approve",
        ["entity_id"],
        "write",
        False,
    ),
    "analytics.dashboard_today": ("GET", "/api/dashboard/today", [], "read", False),
    "analytics.table_query": ("POST", "/api/tables/query", [], "read", False),
    "analytics.table_export_excel": ("POST", "/api/tables/export", [], "write", False),
    "analytics.table_export_1c": ("POST", "/api/tables/export-1c", [], "write", False),
    "analytics.table_import_excel": ("POST", "/api/tables/import", [], "write", False),
    "analytics.table_apply_diff": ("POST", "/api/tables/apply-diff", [], "write", False),
    "analytics.table_inline_edit": ("POST", "/api/tables/inline-edit", [], "write", False),
    "analytics.table_list_views": ("GET", "/api/tables/views", [], "read", False),
    "analytics.table_create_view": ("POST", "/api/tables/views", [], "write", False),
    "analytics.compare_list": ("GET", "/api/compare", [], "read", False),
    "analytics.compare_create": ("POST", "/api/compare", [], "write", False),
    "analytics.compare_get": ("GET", "/api/compare/{entity_id}", ["entity_id"], "read", False),
    "analytics.compare_align": (
        "POST",
        "/api/compare/{entity_id}/align",
        ["entity_id"],
        "write",
        False,
    ),
    "analytics.compare_decide": (
        "POST",
        "/api/compare/{entity_id}/decide",
        ["entity_id"],
        "write",
        False,
    ),
    "analytics.compare_summary": (
        "GET",
        "/api/compare/{entity_id}/summary",
        ["entity_id"],
        "read",
        False,
    ),
    "analytics.collection_list": ("GET", "/api/collections", [], "read", False),
    "analytics.collection_create": ("POST", "/api/collections", [], "write", False),
    "analytics.collection_get": (
        "GET",
        "/api/collections/{entity_id}",
        ["entity_id"],
        "read",
        False,
    ),
    "analytics.collection_summarize": (
        "POST",
        "/api/collections/{entity_id}/summarize",
        ["entity_id"],
        "write",
        False,
    ),
    "analytics.collection_search": (
        "GET",
        "/api/collections/{entity_id}/search",
        ["entity_id"],
        "read",
        False,
    ),
    "analytics.collection_add_item": (
        "POST",
        "/api/collections/{entity_id}/items",
        ["entity_id"],
        "write",
        False,
    ),
    "analytics.collection_suggest": (
        "GET",
        "/api/collections/{entity_id}/suggest",
        ["entity_id"],
        "read",
        False,
    ),
    "analytics.collection_timeline": (
        "GET",
        "/api/collections/{entity_id}/timeline",
        ["entity_id"],
        "read",
        False,
    ),
    "analytics.collection_close": (
        "POST",
        "/api/collections/{entity_id}/close",
        ["entity_id"],
        "write",
        False,
    ),
    "analytics.calendar_events": ("GET", "/api/calendar/events", [], "read", False),
    "analytics.calendar_upcoming": ("GET", "/api/calendar/upcoming", [], "read", False),
    "analytics.calendar_create_reminder": ("POST", "/api/calendar/reminders", [], "write", False),
    "analytics.calendar_extract_dates": ("POST", "/api/calendar/extract-dates", [], "write", False),
    "analytics.calendar_generate_followup": (
        "POST",
        "/api/calendar/reminders/{entity_id}/generate-followup",
        ["entity_id"],
        "write",
        False,
    ),
    "analytics.auto_approval_list": ("GET", "/api/auto-approval-rules", [], "read", False),
    "analytics.auto_approval_create": ("POST", "/api/auto-approval-rules", [], "write", True),
    "analytics.auto_approval_check": ("POST", "/api/auto-approval-rules/check", [], "write", False),
    "agent_control.task_create": ("POST", "/api/agent/tasks", [], "write", True),
    "agent_control.task_propose": ("POST", "/api/agent/tasks/propose", [], "write", False),
    "agent_control.task_decide": (
        "POST",
        "/api/agent/tasks/{entity_id}/decide",
        ["entity_id"],
        "write",
        True,
    ),
    "agent_control.task_run": (
        "POST",
        "/api/agent/tasks/{entity_id}/run",
        ["entity_id"],
        "write",
        True,
    ),
    "agent_control.capability_propose": (
        "POST",
        "/api/agent/capabilities/propose",
        [],
        "write",
        False,
    ),
    "agent_control.capability_status": (
        "GET",
        "/api/agent/capabilities/{proposal_id}/status",
        ["proposal_id"],
        "read",
        False,
    ),
    "agent_control.approval_list": ("GET", "/api/approvals/pending", [], "read", False),
    "agent_control.approval_status": (
        "GET",
        "/api/approvals/{entity_id}",
        ["entity_id"],
        "read",
        False,
    ),
    "agent_control.config_status": ("GET", "/api/agent/control-plane/status", [], "read", False),
    "agent_control.ai_config_get": ("GET", "/api/ai/config", [], "read", False),
    "agent_control.ai_config_set": ("PATCH", "/api/ai/config", [], "write", True),
    "image_studio.generate": ("POST", "/api/image-gen/generate", [], "write", False),
    "image_studio.list": ("GET", "/api/image-gen", [], "read", False),
    "image_studio.get": ("GET", "/api/image-gen/{generation_id}", ["generation_id"], "read", False),
    "image_studio.accept": (
        "POST",
        "/api/image-gen/{generation_id}/accept",
        ["generation_id"],
        "write",
        False,
    ),
    "image_studio.iterate": (
        "POST",
        "/api/image-gen/{generation_id}/iterate",
        ["generation_id"],
        "write",
        False,
    ),
    "image_studio.prompt_help": ("POST", "/api/image-gen/prompt-help", [], "read", False),
    "image_studio.list_workflows": ("GET", "/api/image-gen/workflows/list", [], "read", False),
    "image_studio.techdraw": ("POST", "/api/image-gen/techdraw", [], "write", False),
    "image_studio.accept_techdraw": (
        "POST",
        "/api/image-gen/{generation_id}/accept-techdraw",
        ["generation_id"],
        "write",
        False,
    ),
    "image_studio.accept_vectorize": (
        "POST",
        "/api/image-gen/{generation_id}/accept-vectorize",
        ["generation_id"],
        "write",
        False,
    ),
    "image_studio.get_ir": (
        "GET",
        "/api/image-gen/{generation_id}/ir",
        ["generation_id"],
        "read",
        False,
    ),
    "cad_review.list": ("GET", "/api/image-gen", [], "read", False),
    "cad_review.get": ("GET", "/api/image-gen/{generation_id}", ["generation_id"], "read", False),
    "cad_review.get_ir": (
        "GET",
        "/api/image-gen/{generation_id}/ir",
        ["generation_id"],
        "read",
        False,
    ),
    "cad_review.full_check": (
        "POST",
        "/api/image-gen/{generation_id}/ir/full-check",
        ["generation_id"],
        "write",
        False,
    ),
}

TOOLS = {
    name: ToolDefinition(
        name=name, method=m, path=p, path_params=tuple(ps), effect=e, admin_only=admin
    )
    for name, (m, p, ps, e, admin) in _OPERATIONS.items()
}


def dispatch_routes() -> dict:
    routes: dict = {}
    for tool in TOOLS.values():
        capability, action = tool.name.split(".", 1)
        routes.setdefault(capability, {})[action] = (tool.method, tool.path, list(tool.path_params))
    return routes


def get_tool(capability: str, action: str) -> ToolDefinition | None:
    return TOOLS.get(f"{capability}.{action}")
