"""initial_schema

Revision ID: 25c59714003e
Revises: 
Create Date: 2026-04-24 20:03:40.289670
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PG_UUID


# revision identifiers, used by Alembic.
revision: str = '25c59714003e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_cards',
    sa.Column('anomaly_type', sa.Enum('duplicate', 'new_supplier', 'requisite_change', 'price_spike', 'invoice_email_mismatch', 'unknown_item', name='anomalytype'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='anomalyseverity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'false_positive', 'escalated', name='anomalystatus'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_cards_entity_id'), 'anomaly_cards', ['entity_id'], unique=False)
    op.create_table('approvals',
    sa.Column('action_type', sa.Enum('invoice_approve', 'invoice_reject', 'email_send', 'anomaly_resolve', 'table_apply_diff', 'norm_activate_rule', 'compare_decide', name='approvalactiontype'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'delegated', 'expired', name='approvalstatus'), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('delegated_to', sa.String(length=100), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_timeline_events',
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_timeline_events_entity_id'), 'audit_timeline_events', ['entity_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_event_date'), 'calendar_events', ['event_date'], unique=False)
    op.create_table('canonical_items',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_items_name'), 'canonical_items', ['name'], unique=False)
    op.create_table('collections',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)
    op.create_table('compare_sessions',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('invoice_ids', sa.JSON(), nullable=False),
    sa.Column('alignment', sa.JSON(), nullable=True),
    sa.Column('decision', sa.JSON(), nullable=True),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handovers',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('from_user', sa.String(length=100), nullable=False),
    sa.Column('to_user', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalization_rules',
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('replacement', sa.Text(), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'active', 'disabled', 'rejected', name='normrulestatus'), nullable=False),
    sa.Column('source_corrections', sa.Integer(), nullable=False),
    sa.Column('suggested_by', sa.String(length=50), nullable=False),
    sa.Column('activated_by', sa.String(length=100), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apply_count', sa.Integer(), nullable=False),
    sa.Column('last_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalization_rules_field_name'), 'normalization_rules', ['field_name'], unique=False)
    op.create_table('parties',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('supplier', 'buyer', 'both', name='partyrole'), nullable=False),
    sa.Column('bank_name', sa.String(length=500), nullable=True),
    sa.Column('bank_bik', sa.String(length=9), nullable=True),
    sa.Column('bank_account', sa.String(length=20), nullable=True),
    sa.Column('corr_account', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_inn'), 'parties', ['inn'], unique=False)
    op.create_table('saved_queries',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('nl_text', sa.Text(), nullable=False),
    sa.Column('structured_query', sa.JSON(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('is_alert', sa.Boolean(), nullable=False),
    sa.Column('alert_cron', sa.String(length=50), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_views',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('sort_by', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.String(length=4), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snoozes',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_items',
    sa.Column('collection_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=100), nullable=False),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_actions',
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('draft_data', sa.JSON(), nullable=False),
    sa.Column('approval_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_threads',
    sa.Column('subject', sa.String(length=1000), nullable=False),
    sa.Column('mailbox', sa.String(length=100), nullable=False),
    sa.Column('party_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('calendar_event_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['calendar_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_remind_at'), 'reminders', ['remind_at'], unique=False)
    op.create_table('supplier_profiles',
    sa.Column('party_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('avg_processing_days', sa.Float(), nullable=True),
    sa.Column('last_invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id')
    )
    op.create_table('email_messages',
    sa.Column('thread_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('message_id_header', sa.String(length=500), nullable=True),
    sa.Column('in_reply_to', sa.String(length=500), nullable=True),
    sa.Column('mailbox', sa.String(length=100), nullable=False),
    sa.Column('from_address', sa.String(length=500), nullable=False),
    sa.Column('to_addresses', sa.JSON(), nullable=True),
    sa.Column('cc_addresses', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachment_count', sa.Integer(), nullable=False),
    sa.Column('attachments_meta', sa.JSON(), nullable=True),
    sa.Column('is_inbound', sa.Boolean(), nullable=False),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id_header')
    )
    op.create_table('documents',
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.Enum('invoice', 'letter', 'contract', 'drawing', 'commercial_offer', 'act', 'waybill', 'other', name='documenttype'), nullable=True),
    sa.Column('doc_type_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ingested', 'classifying', 'extracting', 'needs_review', 'approved', 'rejected', 'archived', name='documentstatus'), nullable=False),
    sa.Column('source_channel', sa.String(length=50), nullable=True),
    sa.Column('source_email_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_email_id'], ['email_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_table('document_extractions',
    sa.Column('document_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_links',
    sa.Column('document_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('linked_entity_type', sa.String(length=50), nullable=False),
    sa.Column('linked_entity_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('document_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('document_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('supplier_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('buyer_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'needs_review', 'approved', 'rejected', 'paid', name='invoicestatus'), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_table('extraction_fields',
    sa.Column('extraction_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('confidence_reason', sa.Enum('high_quality_ocr', 'low_quality_ocr', 'ambiguous_value', 'missing_field', 'format_mismatch', 'arithmetic_error', 'normalization_applied', name='confidencereason'), nullable=True),
    sa.Column('bbox_page', sa.Integer(), nullable=True),
    sa.Column('bbox_x', sa.Float(), nullable=True),
    sa.Column('bbox_y', sa.Float(), nullable=True),
    sa.Column('bbox_w', sa.Float(), nullable=True),
    sa.Column('bbox_h', sa.Float(), nullable=True),
    sa.Column('human_corrected', sa.Boolean(), nullable=False),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['document_extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_lines',
    sa.Column('invoice_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('canonical_item_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox_data', sa.JSON(), nullable=True),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history_entries',
    sa.Column('canonical_item_id', PG_UUID(as_uuid=True), nullable=False),
    sa.Column('supplier_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('invoice_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('invoice_line_id', PG_UUID(as_uuid=True), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', PG_UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_item_id'], ['canonical_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_entries_canonical_item_id'), 'price_history_entries', ['canonical_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_entries_canonical_item_id'), table_name='price_history_entries')
    op.drop_table('price_history_entries')
    op.drop_table('invoice_lines')
    op.drop_table('extraction_fields')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('document_versions')
    op.drop_table('document_links')
    op.drop_table('document_extractions')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('email_messages')
    op.drop_table('supplier_profiles')
    op.drop_index(op.f('ix_reminders_remind_at'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('email_threads')
    op.drop_table('draft_actions')
    op.drop_table('collection_items')
    op.drop_table('snoozes')
    op.drop_table('saved_views')
    op.drop_table('saved_queries')
    op.drop_index(op.f('ix_parties_inn'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_normalization_rules_field_name'), table_name='normalization_rules')
    op.drop_table('normalization_rules')
    op.drop_table('handovers')
    op.drop_table('compare_sessions')
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('collections')
    op.drop_index(op.f('ix_canonical_items_name'), table_name='canonical_items')
    op.drop_table('canonical_items')
    op.drop_index(op.f('ix_calendar_events_event_date'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_audit_timeline_events_entity_id'), table_name='audit_timeline_events')
    op.drop_table('audit_timeline_events')
    op.drop_table('audit_logs')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_anomaly_cards_entity_id'), table_name='anomaly_cards')
    op.drop_table('anomaly_cards')
    # ### end Alembic commands ###
